# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AnytimeFitness' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnytimeFitness
	pod 'Firebase/Core'
	pod 'FirebaseUI/Auth'
	pod 'Firebase/Firestore'
	pod 'SwiftLint'
end
